name: Gitee DiscuzX - Upload with Beijing Time

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # 北京时间 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Get Beijing Date
        id: date
        run: |
          beijing_date=$(TZ=Asia/Shanghai date +%Y%m%d)
          echo "date=$beijing_date" >> $GITHUB_ENV

      - name: Clone from Gitee
        run: |
          git clone https://gitee.com/Discuz/DiscuzX.git discuzx

      - name: Upload upload directory with Beijing date
        uses: actions/upload-artifact@v4
        with:
          name: DiscuzX-upload-${{ env.date }}
          path: discuzx/upload/
