name: Gitee DiscuzX - Upload with Beijing Time

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # 北京时间 00:00

permissions:
  contents: write  # 需要写入权限来创建release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Get Beijing Date
        id: date
        run: |
          beijing_date=$(TZ=Asia/Shanghai date +%Y%m%d)
          echo "date=$beijing_date" >> $GITHUB_ENV

      - name: Clone from Gitee
        run: |
          git clone https://gitee.com/Discuz/DiscuzX.git discuzx

      - name: Archive Upload Directory
        run: |
          cd discuzx && zip -r ../DiscuzX-upload-${{ env.date }}.zip upload/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ env.date }}
          name: DiscuzX Upload - ${{ env.date }}
          draft: false
          prerelease: false
          files: |
            DiscuzX-upload-${{ env.date }}.zip
