name: Gitee DiscuzX - Upload upload Directory

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone from Gitee
        run: |
          git clone https://gitee.com/Discuz/DiscuzX.git discuzx

      - name: Upload upload directory as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DiscuzX-upload
          path: discuzx/upload/
