name: Gitee DiscuzX Code Sync

on:
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0 点运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone from Gitee
        run: |
          git clone https://gitee.com/Discuz/DiscuzX.git discuzx
          cd discuzx
          git checkout master  # 可选：指定分支

      - name: Show directory structure
        run: |
          ls -la discuzx
